add_newline = false

format = """
$directory\
$git_branch\
$kubernetes\
$cmd_duration\
$line_break\
$jobs\
$character\
"""

[kubernetes]
disabled = false
style = "purple"
symbol = ""

[git_branch]
style = "bold yellow"
