#!/bin/sh

wmname LG3D

pkill dunst
pkill picom
pkill polybar
pkill sxhkd
pkill xautolock

bspc config window_gap 0

bspc monitor DVI-D-0 -d 1
bspc monitor HDMI-A-0 -d 2 3 4 5 6 7 8 9
bspc config window_gap 20

dunst &
nm-applet &
picom -f &
polybar main &
sxhkd &

nitrogen --restore

xautolock -time 5 -locker ~/.config/bspwm/lock.sh -detectsleep &

bspc config border_width        0
bspc config single_monocle      true

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus   true

bspc rule -a firefox desktop=1 follow=on
bspc rule -a firefoxdeveloperedition desktop=1 follow=on
bspc rule -a Alacritty desktop=2 follow=on
bspc rule -a Slack desktop=3 follow=on
bspc rule -a KeePassXC desktop=3 follow=on
bspc rule -a Spotify desktop=4 follow=on
bspc rule -a pinentry-gtk-2 state=floating
bspc rule -a AlacrittyFloating desktop=2 follow=on state=floating
bspc rule -a Peek state=floating

bsp-layout set tall 2 --master-size 0.53
